import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import confetti from "canvas-confetti";

import ThreeDCard from "../components/ThreeDCard";
import Toast, { ToastContainer } from "../components/Toast";
import CookingMode from "../components/CookingMode";
import { remixRecipe } from "../utils/api";
import "../styles/FavoritesPage.css";

function FavoritesPage() {
  const navigate = useNavigate();

  // Local storage cookbook states
  const [recipes, setRecipes] = useState([]);
  const [toasts, setToasts] = useState([]);

  // Modal active states
  const [selectedRecipe, setSelectedRecipe] = useState(null); // for viewing full details
  const [deleteConfirmationRecipe, setDeleteConfirmationRecipe] = useState(null);
  const [remixRecipeTarget, setRemixRecipeTarget] = useState(null); // for showing remix modal
  
  // Remix Execution States
  const [customTwistText, setCustomTwistText] = useState("");
  const [remixLoading, setRemixLoading] = useState(false);
  const [remixResult, setRemixResult] = useState(null); // stores generated remixed recipe

  // Active cooking mode state
  const [cookingRecipe, setCookingRecipe] = useState(null);

  // Load cookbook on mount
  useEffect(() => {
    const saved = JSON.parse(localStorage.getItem("savedRecipes")) || [];
    setRecipes(saved);
  }, []);

  // Toast Helpers
  const addToast = (message, type = "success") => {
    const id = Date.now();
    setToasts((prev) => [...prev, { id, message, type }]);
  };

  const removeToast = (id) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  };

  // 1. Click-to-rate 5-star system
  const handleRateRecipe = (recipeId, rating) => {
    const updated = recipes.map((recipe) => {
      if (recipe.id === recipeId) {
        return { ...recipe, rating };
      }
      return recipe;
    });
    setRecipes(updated);
    localStorage.setItem("savedRecipes", JSON.stringify(updated));
    addToast(`Rated recipe ${rating} stars!`, "success");
  };

  // 2. Editable notes: saves on blur
  const handleNotesBlur = (recipeId, notesText) => {
    const updated = recipes.map((recipe) => {
      if (recipe.id === recipeId) {
        return { ...recipe, notes: notesText };
      }
      return recipe;
    });
    setRecipes(updated);
    localStorage.setItem("savedRecipes", JSON.stringify(updated));
    addToast("Notes auto-saved successfully!", "success");
  };

  // 3. Export to clipboard formatted
  const handleExportRecipe = (recipe) => {
    const ratingStars = "★".repeat(recipe.rating) + "☆".repeat(5 - recipe.rating);
    const text = `🍽️ RECIPE: ${recipe.title.toUpperCase()}
🌐 Cuisine: ${recipe.cuisine || "Fusion"}
⏱️ Prep Time: ${recipe.prepTime || "15 mins"} | Cook Time: ${recipe.cookTime || "20 mins"}
⭐ Rating: ${ratingStars}

🥕 INGREDIENTS:
${recipe.ingredients.map((ing) => `- ${ing}`).join("\n")}

👨‍🍳 COOKING STEPS:
${recipe.steps.map((step, idx) => `${idx + 1}. ${step}`).join("\n")}

📝 PERSONAL NOTES:
${recipe.notes || "No notes written yet."}

Generated by Chef's AI Kitchen.`;

    navigator.clipboard.writeText(text)
      .then(() => {
        addToast("Recipe copied to clipboard!", "success");
      })
      .catch(() => {
        addToast("Failed to copy recipe.", "error");
      });
  };

  // 4. Delete with custom confirmation modal
  const triggerDeleteConfirm = (recipe) => {
    setDeleteConfirmationRecipe(recipe);
  };

  const executeDeleteRecipe = () => {
    if (!deleteConfirmationRecipe) return;
    const updated = recipes.filter((r) => r.id !== deleteConfirmationRecipe.id);
    setRecipes(updated);
    localStorage.setItem("savedRecipes", JSON.stringify(updated));
    addToast(`"${deleteConfirmationRecipe.title}" deleted`, "info");
    setDeleteConfirmationRecipe(null);
    setSelectedRecipe(null); // Close details modal if open
  };

  // 5. Remix flows (Vegan, Spicy, Faster, Fewer)
  const triggerRemixModal = (recipe) => {
    setRemixRecipeTarget(recipe);
    setRemixResult(null);
    setCustomTwistText("");
  };

  const handleExecuteRemix = async (twistOption) => {
    if (!remixRecipeTarget) return;

    setRemixLoading(true);
    addToast(`Asking Claude to remix: "${remixRecipeTarget.title}"...`, "info");

    try {
      const remixed = await remixRecipe(remixRecipeTarget, twistOption);
      setRemixResult(remixed);
      
      // Burst confetti for successful remix!
      confetti({
        particleCount: 150,
        spread: 80,
        origin: { y: 0.6 },
        colors: ["#F4A319", "#C1440E", "#3B6B35", "#FFFFFF"],
      });
      addToast("Successfully remixed recipe!", "success");
    } catch (e) {
      console.error(e);
      addToast(e.message || "Failed to remix recipe.", "error");
    } finally {
      setRemixLoading(false);
    }
  };

  const handleSaveRemixToCookbook = () => {
    if (!remixResult) return;

    const newSavedObj = {
      id: `ai-remix-${Date.now()}`,
      title: remixResult.title,
      ingredients: remixResult.ingredients,
      steps: remixResult.steps,
      cuisine: remixResult.cuisine || "Fusion",
      prepTime: remixResult.prepTime || "15 mins",
      cookTime: remixResult.cookTime || "20 mins",
      timestamp: Date.now(),
      rating: 0,
      notes: `Remixed from original "${remixRecipeTarget.title}".`,
    };

    const updated = [newSavedObj, ...recipes];
    setRecipes(updated);
    localStorage.setItem("savedRecipes", JSON.stringify(updated));
    addToast("Saved remixed recipe as new Cookbook card!", "success");
    
    // Close remix flows
    setRemixResult(null);
    setRemixRecipeTarget(null);
  };

  return (
    <div className="cookbook-container">
      {/* Header */}
      <div className="cookbook-header">
        <div className="cookbook-title">
          <span style={{ fontSize: "2rem" }}>📖</span>
          <div>
            <h2 style={{ fontSize: "1.6rem", margin: 0, fontWeight: 700 }}>
              My AI Cookbook
            </h2>
            <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", margin: 0 }}>
              Your collection of rated recipes, personal notes, and creative Claude remixes.
            </p>
          </div>
        </div>
        <button className="back-home-link" onClick={() => navigate("/recipes")}>
          ← Back to Studio
        </button>
      </div>

      {recipes.length === 0 ? (
        /* Empty Cookbook View */
        <div className="empty-cookbook-view">
          <span style={{ fontSize: "3rem", display: "block", marginBottom: "12px" }}>🥣</span>
          <h3 style={{ fontFamily: "var(--font-title)" }}>Cookbook is Empty</h3>
          <p style={{ fontSize: "0.9rem", color: "var(--text-secondary)", margin: "8px 0 var(--spacing-md)" }}>
            Go to the AI Chef's Workshop, craft custom recipes, and tap the heart bookmark to collect them here!
          </p>
          <button className="back-home-link" onClick={() => navigate("/recipes")}>
            Open AI Workshop
          </button>
        </div>
      ) : (
        /* Cookbook Grid */
        <div className="cookbook-grid">
          {recipes.map((recipe) => (
            <ThreeDCard key={recipe.id}>
              <div 
                className="cookbook-card"
                onClick={() => setSelectedRecipe(recipe)}
                style={{ cursor: "pointer" }}
              >
                {/* Card Title & Heart Delete trigger */}
                <div className="cookbook-card-header">
                  <div>
                    <h3 className="cookbook-card-title">{recipe.title}</h3>
                    <div className="cookbook-meta-row" style={{ marginTop: "8px" }}>
                      <span className="cookbook-badge cuisine">🌐 {recipe.cuisine}</span>
                      <span className="cookbook-badge">⏱️ {recipe.prepTime}</span>
                    </div>
                  </div>
                  <span 
                    style={{ fontSize: "1.3rem", color: "var(--accent-terracotta)", padding: "2px" }}
                    onClick={(e) => {
                      e.stopPropagation();
                      triggerDeleteConfirm(recipe);
                    }}
                    title="Delete recipe"
                  >
                    ❤️
                  </span>
                </div>

                {/* 5-Star Ratings */}
                <div 
                  className="star-rating-row"
                  onClick={(e) => e.stopPropagation()} // Prevent card modal
                >
                  {[1, 2, 3, 4, 5].map((star) => (
                    <span
                      key={star}
                      className={`star-icon ${star <= recipe.rating ? "active" : ""}`}
                      onClick={() => handleRateRecipe(recipe.id, star)}
                    >
                      ★
                    </span>
                  ))}
                </div>

                {/* Editable Notes: Saves on Blur */}
                <div 
                  className="cookbook-notes-area"
                  onClick={(e) => e.stopPropagation()} // Prevent card modal
                >
                  <span className="cookbook-notes-label">My Chef Notes</span>
                  <textarea
                    className="cookbook-notes-input"
                    placeholder="Add personal twist details, baking temps, or feedback..."
                    defaultValue={recipe.notes}
                    onBlur={(e) => handleNotesBlur(recipe.id, e.target.value)}
                  />
                </div>

                {/* Actions Grid */}
                <div 
                  className="cookbook-actions-row"
                  onClick={(e) => e.stopPropagation()} // Prevent card modal
                >
                  <button className="cookbook-btn" onClick={() => handleExportRecipe(recipe)}>
                    📋 Export
                  </button>
                  <button className="cookbook-btn remix" onClick={() => triggerRemixModal(recipe)}>
                    🌀 Remix
                  </button>
                  <button className="cookbook-btn delete" onClick={() => triggerDeleteConfirm(recipe)}>
                    🗑️ Delete
                  </button>
                </div>
              </div>
            </ThreeDCard>
          ))}
        </div>
      )}

      {/* MODALS SECTION */}
      <AnimatePresence>
        {/* Detail Modal Overlay */}
        {selectedRecipe && (
          <div className="remix-overlay-backdrop" onClick={() => setSelectedRecipe(null)}>
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="details-modal-card"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                style={{
                  position: "absolute",
                  top: "16px",
                  right: "16px",
                  background: "none",
                  border: "none",
                  fontSize: "1.5rem",
                  cursor: "pointer",
                  color: "var(--text-secondary)",
                }}
                onClick={() => setSelectedRecipe(null)}
              >
                ✕
              </button>

              <h2 style={{ fontFamily: "var(--font-title)", fontSize: "2.1rem", marginBottom: "8px" }}>
                {selectedRecipe.title}
              </h2>
              <div className="cookbook-meta-row" style={{ marginBottom: "20px" }}>
                <span className="cookbook-badge cuisine">🌐 {selectedRecipe.cuisine}</span>
                <span className="cookbook-badge">⏱️ Prep: {selectedRecipe.prepTime}</span>
                <span className="cookbook-badge">🍳 Cook: {selectedRecipe.cookTime}</span>
              </div>

              <h3 style={{ fontSize: "1.3rem", borderBottom: "2px solid var(--border-color)", paddingBottom: "4px", marginBottom: "12px" }}>
                Ingredients
              </h3>
              <ul style={{ paddingLeft: "20px", marginBottom: "20px", lineHeight: "1.7" }}>
                {selectedRecipe.ingredients.map((ing, idx) => (
                  <li key={idx}>{ing}</li>
                ))}
              </ul>

              <h3 style={{ fontSize: "1.3rem", borderBottom: "2px solid var(--border-color)", paddingBottom: "4px", marginBottom: "12px" }}>
                Steps
              </h3>
              <ol style={{ paddingLeft: "20px", marginBottom: "24px", lineHeight: "1.7" }}>
                {selectedRecipe.steps.map((step, idx) => (
                  <li key={idx} style={{ marginBottom: "8px" }}>{step}</li>
                ))}
              </ol>

              <button
                className="btn-start-cooking"
                style={{ marginTop: "12px" }}
                onClick={() => {
                  setCookingRecipe(selectedRecipe);
                  setSelectedRecipe(null);
                }}
              >
                👨‍🍳 Enter Hands-Free Cooking Mode
              </button>
            </motion.div>
          </div>
        )}

        {/* Delete Confirmation Modal Overlay */}
        {deleteConfirmationRecipe && (
          <div className="remix-overlay-backdrop">
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="confirm-delete-card"
            >
              <div className="confirm-delete-icon">🌶️</div>
              <h3 style={{ fontFamily: "var(--font-title)", fontSize: "1.4rem", marginBottom: "8px" }}>
                Remove Recipe?
              </h3>
              <p style={{ fontSize: "0.88rem", color: "var(--text-secondary)", marginBottom: "20px" }}>
                Are you sure you want to delete <strong>"{deleteConfirmationRecipe.title}"</strong> from your Cookbook collection? This action is permanent.
              </p>
              <div style={{ display: "flex", gap: "10px", justifyContent: "center" }}>
                <button
                  className="cookbook-btn"
                  style={{ padding: "8px 16px" }}
                  onClick={() => setDeleteConfirmationRecipe(null)}
                >
                  Cancel
                </button>
                <button
                  className="cookbook-btn delete"
                  style={{ padding: "8px 16px" }}
                  onClick={executeDeleteRecipe}
                >
                  Yes, Delete
                </button>
              </div>
            </motion.div>
          </div>
        )}

        {/* Remix Selection Overlay Modal */}
        {remixRecipeTarget && (
          <div className="remix-overlay-backdrop" onClick={() => !remixLoading && setRemixRecipeTarget(null)}>
            <motion.div
              initial={{ y: 50, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: 50, opacity: 0 }}
              className="remix-modal-card"
              onClick={(e) => e.stopPropagation()}
            >
              {!remixResult ? (
                /* Remix Selection Dashboard */
                <>
                  <h3 className="remix-modal-title">🌀 AI Recipe Remix Studio</h3>
                  <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "8px" }}>
                    Select a creative twist options or write your custom culinary request for Claude.
                  </p>

                  {remixLoading ? (
                    /* Shimmer Loader while Claude remix is cooking */
                    <div style={{ display: "flex", flexDirection: "column", gap: "12px", padding: "16px 0" }}>
                      <div className="shimmer-skeleton" style={{ height: "40px", borderRadius: "8px" }} />
                      <div className="shimmer-skeleton" style={{ height: "40px", borderRadius: "8px", width: "80%" }} />
                      <div className="shimmer-skeleton" style={{ height: "40px", borderRadius: "8px", width: "90%" }} />
                      <p style={{ textAlign: "center", color: "var(--accent-saffron)", fontWeight: "600", marginTop: "12px" }}>
                        Claude Chef is baking your remixed recipe...
                      </p>
                    </div>
                  ) : (
                    /* Remix list options */
                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                      <button className="remix-option-chip" onClick={() => handleExecuteRemix("Vegan twist (No eggs, dairy, meat)")}>
                        <span>🌿 Make it Vegan</span>
                        <span>→</span>
                      </button>
                      <button className="remix-option-chip" onClick={() => handleExecuteRemix("Fiery Spicy twist (Added chilies, peppers)")}>
                        <span>🌶️ Make it Spicy</span>
                        <span>→</span>
                      </button>
                      <button className="remix-option-chip" onClick={() => handleExecuteRemix("Fast prep twist (Cook under 15 minutes)")}>
                        <span>⚡ Make it Faster to Cook</span>
                        <span>→</span>
                      </button>
                      <button className="remix-option-chip" onClick={() => handleExecuteRemix("Minimalist twist (Maximum 5 ingredients total)")}>
                        <span>📦 Use Fewer Ingredients</span>
                        <span>→</span>
                      </button>

                      <div style={{ marginTop: "8px" }}>
                        <span style={{ fontSize: "0.8rem", fontWeight: "600", color: "var(--text-secondary)", display: "block", marginBottom: "4px" }}>
                          Custom Creative Twist
                        </span>
                        <div style={{ display: "flex", gap: "8px" }}>
                          <input
                            type="text"
                            className="remix-custom-input"
                            placeholder="e.g., make it Gluten-free, add shrimp, make it sweet"
                            value={customTwistText}
                            onChange={(e) => setCustomTwistText(e.target.value)}
                          />
                          <button
                            className="cookbook-btn remix"
                            style={{ padding: "0 16px" }}
                            disabled={!customTwistText.trim()}
                            onClick={() => handleExecuteRemix(customTwistText.trim())}
                          >
                            Go
                          </button>
                        </div>
                      </div>

                      <div className="remix-modal-buttons">
                        <button className="cookbook-btn" onClick={() => setRemixRecipeTarget(null)}>
                          Cancel
                        </button>
                      </div>
                    </div>
                  )}
                </>
              ) : (
                /* Remix Generation Result Viewer */
                <div style={{ maxHeight: "80vh", overflowY: "auto" }}>
                  <h3 className="remix-modal-title" style={{ color: "var(--accent-saffron)", marginBottom: "4px" }}>
                    ✨ Chef's Remixed Twist!
                  </h3>
                  <h2 style={{ fontFamily: "var(--font-title)", fontSize: "1.8rem", marginBottom: "16px" }}>
                    {remixResult.title}
                  </h2>

                  <h4 style={{ fontWeight: 600, color: "var(--text-primary)", marginBottom: "8px" }}>
                    Modified Ingredients
                  </h4>
                  <ul style={{ paddingLeft: "20px", fontSize: "0.9rem", marginBottom: "16px", lineHeight: "1.6" }}>
                    {remixResult.ingredients.map((ing, idx) => (
                      <li key={idx}>{ing}</li>
                    ))}
                  </ul>

                  <h4 style={{ fontWeight: 600, color: "var(--text-primary)", marginBottom: "8px" }}>
                    Modified Steps
                  </h4>
                  <ol style={{ paddingLeft: "20px", fontSize: "0.9rem", marginBottom: "20px", lineHeight: "1.6" }}>
                    {remixResult.steps.map((step, idx) => (
                      <li key={idx} style={{ marginBottom: "6px" }}>{step}</li>
                    ))}
                  </ol>

                  <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end" }}>
                    <button className="cookbook-btn" onClick={() => setRemixResult(null)}>
                      Back
                    </button>
                    <button className="cookbook-btn remix" onClick={handleSaveRemixToCookbook}>
                      💾 Save Remixed Recipe
                    </button>
                  </div>
                </div>
              )}
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Fullscreen voice Cooking Mode inside Cookbook details */}
      {cookingRecipe && (
        <CookingMode recipe={cookingRecipe} onClose={() => setCookingRecipe(null)} />
      )}

      {/* Cookbook Toast Container */}
      <ToastContainer>
        <AnimatePresence>
          {toasts.map((toast) => (
            <Toast
              key={toast.id}
              message={toast.message}
              type={toast.type}
              onClose={() => removeToast(toast.id)}
            />
          ))}
        </AnimatePresence>
      </ToastContainer>
    </div>
  );
}

export default FavoritesPage;
